---
- name: Mise à jour du cache APT
  apt:
    update_cache: yes
  become: yes

- name: Installer les paquets de base
  apt:
    name:
      - sudo
      - vim
      - nano
      - curl
      - wget
      - iputils-ping
      - net-tools
      - rsync
      - snmp
    state: present
  become: yes

- name: Vérifier que l'utilisateur ansible existe
  user:
    name: ansible
    groups: sudo
    append: yes
  become: yes

- name: Autoriser sudo sans mot de passe pour ansible
  copy:
    dest: /etc/sudoers.d/ansible
    content: "ansible ALL=(ALL) NOPASSWD:ALL\n"
    owner: root
    group: root
    mode: "0440"
  become: yes

