---
- name: Configuration commune
  hosts: glpiweb,centreonmaster,centreoncollector,webtest,backup
  become: yes
  roles:
    - common

- name: Serveur web de test
  hosts: webtest
  become: yes
  roles:
    - apache_test
    - snmp_agent

